name: pr-velidation
on: 
  pull_request:
    branches:
      - develop
jobs:
  develop-pr-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint HTML and CSS
        run: |
          npx htmlint "**/*.html"
          npx stylelint "**/*.css" 
  develop-build: # auto combine target and feature commits in temp branch 
    runs-on: ubuntu-latest
    steps: 
      - name: Build Website
        run: npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"
